name: Release
on:
  push:
    tags: ['*']
env:
    GITHUB_TAG: ${{ github.ref }}
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v2.3.4
            -
                name: Configure Java
                uses: actions/setup-java@v2
                with:
                    java-version: 11
                    distribution: adopt-openj9
            -
                name: Tests
                run: ./gradlew check
    common:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v2.3.4
            -
                name: Configure Java
                uses: actions/setup-java@v2
                with:
                    java-version: 11
                    distribution: adopt-openj9
            -
                name: Build Metadata Publication
                run: ./gradlew publishKotlinMultiplatformPublicationToBuildRepository -Pversion=${GITHUB_TAG/refs\/tags\//}
            -
                name: Build Android Publication
                run: ./gradlew publishAndroidReleasePublicationToBuildRepository publishAndroidDebugPublicationToBuildRepository -Pversion=${GITHUB_TAG/refs\/tags\//}
            -
                name: Zip All Publications
                run: ./gradlew zipPublications
            -
                name: Archive
                uses: actions/upload-artifact@v2
                with:
                    name: Common Publications
                    path: build/distributions/publications.zip
            -
                name: Maven Publish
                env:
                    GITHUB_TAG: ${{ github.ref }}
                    ORG_GRADLE_PROJECT_mavenUser: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
                    ORG_GRADLE_PROJECT_mavenPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
                    ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.PGP_INK_CI_KEYID }}
                    ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_INK_CI_PRIVATE }}
                    ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PGP_INK_CI_PASSWORD }}
                run: >
                    ./gradlew
                    publishKotlinMultiplatformPublicationToMavenCentralRepository
                    publishAndroidReleasePublicationToMavenCentralRepository
                    publishAndroidDebugPublicationToMavenCentralRepository
                    -Pversion=${GITHUB_TAG/refs\/tags\//}
    
